sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t michaelferns/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michaelferns/docker-react npm run test